In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/Testing_data.csv")
df

,date,temperature,humidity,pressure,label,hour,month,cos_hour,sin_hour,cos_month,sin_month,temp_gradient,humid_gradient,press_gradient,elevation,latitude,longitude
0,2019-12-31 18:30:00+00:00,13.400000,90.938438,1016.566284,genuine,18,12,-1.836970e-16,-1.000000,1.000000,-2.449294e-16,NaN,NaN,NaN,11.0,22.56263,88.36304
1,2019-12-31 19:30:00+00:00,12.900000,91.507561,1016.363953,genuine,19,12,2.588190e-01,-0.965926,1.000000,-2.449294e-16,-0.500000,0.569122,-0.202332,11.0,22.56263,88.36304
2,2019-12-31 20:30:00+00:00,12.350000,92.693878,1016.061829,genuine,20,12,5.000000e-01,-0.866025,1.000000,-2.449294e-16,-0.549999,1.186317,-0.302124,11.0,22.56263,88.36304
3,2019-12-31 21:30:00+00:00,12.100000,93.918091,1016.160706,genuine,21,12,7.071068e-01,-0.707107,1.000000,-2.449294e-16,-0.250000,1.224213,0.098877,11.0,22.56263,88.36304
4,2019-12-31 22:30:00+00:00,11.350000,95.142830,1016.157227,genuine,22,12,8.660254e-01,-0.500000,1.000000,-2.449294e-16,-0.750000,1.224739,-0.003479,11.0,22.56263,88.36304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43867,2025-01-01 13:30:00+00:00,20.200001,67.099625,1013.700806,genuine,13,1,-9.659258e-01,-0.258819,0.866025,5.000000e-01,-0.549999,2.448486,0.696899,11.0,22.56263,88.36304
43868,2025-01-01 14:30:00+00:00,19.500000,70.302605,1014.496643,genuine,14,1,-8.660254e-01,-0.500000,0.866025,5.000000e-01,-0.700001,3.202980,0.795837,11.0,22.56263,88.36304
43869,2025-01-01 15:30:00+00:00,18.750000,73.666794,1014.792725,genuine,15,1,-7.071068e-01,-0.707107,0.866025,5.000000e-01,-0.750000,3.364189,0.296082,11.0,22.56263,88.36304
43870,2025-01-01 16:30:00+00:00,18.049999,77.471115,1014.889771,genuine,16,1,-5.000000e-01,-0.866025,0.866025,5.000000e-01,-0.700001,3.804321,0.097046,11.0,22.56263,88.36304
43871,2025-01-01 17:30:00+00:00,17.350000,81.227196,1014.786682,genuine,17,1,-2.588190e-01,-0.965926,0.866025,5.000000e-01,-0.699999,3.756081,-0.103088,11.0,22.56263,88.36304

In [3]:
df["6_hour_gradient_temp"] = df['temperature'].diff(periods=6)
df["6_hour_gradient_press"] = df['pressure'].diff(periods=6)
df["6_hour_gradient_humid"] = df['humidity'].diff(periods=6)
df = df.dropna(axis=0).reset_index()

In [4]:
df.drop(columns=['hour', 'month'], inplace=True)

In [5]:
df.describe()

,index,temperature,humidity,pressure,cos_hour,sin_hour,cos_month,sin_month,temp_gradient,humid_gradient,press_gradient,elevation,latitude,longitude,6_hour_gradient_temp,6_hour_gradient_press,6_hour_gradient_humid
count,43866.000000,43866.000000,43866.000000,43866.000000,4.386600e+04,4.386600e+04,4.386600e+04,4.386600e+04,43866.000000,43866.000000,43866.000000,43866.0,4.386600e+04,4.386600e+04,43866.000000,43866.000000,43866.000000
mean,21938.500000,30.612769,77.112967,1004.786553,-7.518071e-05,9.797741e-05,-1.466616e-03,-4.220193e-03,0.000135,-0.000310,-0.000045,11.0,2.256263e+01,8.836304e+01,0.000936,-0.000283,-0.002841
std,12663.167791,45.274767,17.231563,21.954225,7.071229e-01,7.071068e-01,7.084420e-01,7.057711e-01,2.922217,5.879261,1.789592,0.0,3.552754e-15,4.263305e-14,7.737512,4.137519,20.364492
min,6.000000,-309.434481,-132.226954,748.945943,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-280.643144,-186.389735,-90.024459,11.0,2.256263e+01,8.836304e+01,-283.292437,-90.926619,-222.386912
25%,10972.250000,23.100000,68.107727,1001.842407,-7.071068e-01,-7.071068e-01,-8.660254e-01,-8.660254e-01,-0.500000,-2.678723,-0.491760,11.0,2.256263e+01,8.836304e+01,-2.900000,-1.704193,-12.126991
50%,21938.500000,27.100000,81.919495,1006.734741,-1.836970e-16,1.224647e-16,-1.836970e-16,-2.449294e-16,-0.100000,0.255962,0.000000,11.0,2.256263e+01,8.836304e+01,-0.799999,0.172333,2.781860
75%,32904.750000,30.000000,90.592447,1011.726074,7.071068e-01,7.071068e-01,8.660254e-01,5.000000e-01,0.600707,2.186324,0.498169,11.0,2.256263e+01,8.836304e+01,2.900002,2.008728,12.748369
max,43871.000000,311.642438,209.049877,1104.120711,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,334.034482,174.742499,255.590156,11.0,2.256263e+01,8.836304e+01,334.134482,255.675732,163.805417