In [1]:
import pandas as pd
from weather_anamoly.utils import ImportCoordinates, ImportData, AnomalyInjection

In [ ]:
df = pd.read_csv("data/2016_to_2023_kolkata.csv", parse_dates=['date'], index_col=0)

In [3]:
anomaly_injection = AnomalyInjection()

In [4]:
df_anomalied = anomaly_injection.inject_anomalies(df=df.copy())

In [5]:
df_anomalied.set_index('date')

                           temperature   humidity    pressure    label
date
2015-12-31 18:30:00+00:00    15.911000  87.918816  1017.17680  genuine
2015-12-31 19:30:00+00:00    15.611000  88.465645  1016.97590  genuine
2015-12-31 20:30:00+00:00    14.861000  91.036360  1016.77264  genuine
2015-12-31 21:30:00+00:00    14.361000  92.200000  1016.37100  genuine
2015-12-31 22:30:00+00:00    14.061001  93.091220  1016.76874  genuine
...                                ...        ...         ...      ...
2024-01-01 13:30:00+00:00    17.850000  84.223050  1014.88880  genuine
2024-01-01 14:30:00+00:00    18.600000  80.350850  1015.19150  genuine
2024-01-01 15:30:00+00:00    18.100000  81.587000  1015.18933  genuine
2024-01-01 16:30:00+00:00    18.350000  80.316990  1015.19070  genuine
2024-01-01 17:30:00+00:00    17.150000  85.238260  1014.88560  genuine

[70152 rows x 4 columns]

In [6]:
df_anomalied.label.unique()

<StringArray>
['genuine', 'spike', 'fault', 'frozen']
Length: 4, dtype: str

In [7]:
df_anomalied['label'].value_counts()

label
genuine    61655
fault       8262
frozen       189
spike         46
Name: count, dtype: int64

In [15]:
import numpy as np

In [12]:
df = df_anomalied.set_index('date')

In [ ]:
df['cos_hour'] = np.cos(2*np.pi*df.index.hour/24)
df['sin_hour'] = np.sin(2*np.pi*df.index.hour/24)
df['cos_month'] = np.cos(2*np.pi*df.index.month/12)
df['sin_month'] = np.sin(2*np.pi*df.index.month/12)
df['temp_gradient'] = df['temperature'].diff()
df['humid_gradient'] = df['humidity'].diff()
df['press_gradient'] = df['pressure'].diff()
df

,temperature,humidity,pressure,label,hour,month,cos_hour,sin_hour,cos_month,sin_month,temp_gradient,humid_gradient,press_gradient
date,,,,,,,,,,,,,
2015-12-31 19:30:00+00:00,15.611000,88.465645,1016.97590,genuine,19,12,0.258819,-0.965926,1.000000,-2.449294e-16,-0.300000,0.546829,-0.20090
2015-12-31 20:30:00+00:00,14.861000,91.036360,1016.77264,genuine,20,12,0.500000,-0.866025,1.000000,-2.449294e-16,-0.750000,2.570715,-0.20326
2015-12-31 21:30:00+00:00,14.361000,92.200000,1016.37100,genuine,21,12,0.707107,-0.707107,1.000000,-2.449294e-16,-0.500000,1.163640,-0.40164
2015-12-31 22:30:00+00:00,14.061001,93.091220,1016.76874,genuine,22,12,0.866025,-0.500000,1.000000,-2.449294e-16,-0.299999,0.891220,0.39774
2015-12-31 23:30:00+00:00,13.961000,93.086020,1017.46760,genuine,23,12,0.965926,-0.258819,1.000000,-2.449294e-16,-0.100001,-0.005200,0.69886
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-01 13:30:00+00:00,17.850000,84.223050,1014.88880,genuine,13,1,-0.965926,-0.258819,0.866025,5.000000e-01,-0.050000,-1.093780,0.79896
2024-01-01 14:30:00+00:00,18.600000,80.350850,1015.19150,genuine,14,1,-0.866025,-0.500000,0.866025,5.000000e-01,0.750000,-3.872200,0.30270
2024-01-01 15:30:00+00:00,18.100000,81.587000,1015.18933,genuine,15,1,-0.707107,-0.707107,0.866025,5.000000e-01,-0.500000,1.236150,-0.00217
2024-01-01 16:30:00+00:00,18.350000,80.316990,1015.19070,genuine,16,1,-0.500000,-0.866025,0.866025,5.000000e-01,0.250000,-1.270010,0.00137
2024-01-01 17:30:00+00:00,17.150000,85.238260,1014.88560,genuine,17,1,-0.258819,-0.965926,0.866025,5.000000e-01,-1.200000,4.921270,-0.30510

In [19]:
df.to_csv("data/anomaly_labelled_data.csv")